name: Reserve next daily lesson
on:
  schedule:
    - cron: "0 13 * * 0"
    - cron: "0 13 * * 1"
    - cron: "0 13 * * 2"
    - cron: "0 13 * * 3"
    - cron: "0 13 * * 4"
    - cron: "0 13 * * 5"
    - cron: "0 13 * * 6"
  workflow_dispatch:
jobs:
  reserve:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-firefox-debug:3.141
    container:
      image: ghcr.io/musaprg/rarejobctl:latest
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        RAREJOB_EMAIL: ${{ secrets.RAREJOB_EMAIL }}
        RAREJOB_PASSWORD: ${{ secrets.RAREJOB_PASSWORD }}
        RESERVATION_TIME: "9:30"
        RESERVATION_MARGIN_MINUTES: "0"
    steps:
      - name: Reserve a next lesson
        # Skip Fri and Sat reservation i.e. I don't want to do english lesson on weekends.
        if: github.event.schedule != '0 13 * * 5' && github.event.schedule != '0 13 * * 6'
        env:
          TZ: "Asia/Tokyo" # Timezone is set to JST
        run: |
          export TOMORROW_YEAR=$(date -d'+1day' +'%-Y')
          export TOMORROW_MONTH=$(date -d'+1day' +'%-m')
          export TOMORROW_DAY_OF_MONTH=$(date -d'+1day' +'%-d')
          rarejobctl \
            -selenium-host selenium \
            -selenium-port 4444 \
            -selenium-browser-name firefox \
            -year ${TOMORROW_YEAR} \
            -month ${TOMORROW_MONTH} \
            -day ${TOMORROW_DAY_OF_MONTH} \
            -time ${RESERVATION_TIME} \
            -margin ${RESERVATION_MARGIN_MINUTES}
